# 산탄데르 고객 만족 예측

## 1. 라이브러리 로드

In [22]:
import pandas as pd
import numpy as np

from xgboost import XGBClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score, roc_auc_score

import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

## 2. 데이터 로드

In [11]:
train = pd.read_csv("./santander_customer_satisfaction/train_snatander.csv", encoding='latin-1')
train

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76015,151829,2,48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60926.490000,0
76016,151830,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118634.520000,0
76017,151835,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74028.150000,0
76018,151836,2,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84278.160000,0
76019,151838,2,46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [12]:
test = pd.read_csv("./santander_customer_satisfaction/test.csv", encoding='latin-1')
test

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
0,2,2,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40532.100000
1,5,2,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45486.720000
2,6,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46993.950000
3,7,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,187898.610000
4,9,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73649.730000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75813,151831,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40243.200000
75814,151832,2,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,146961.300000
75815,151833,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,167299.770000
75816,151834,2,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016
75817,151837,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016

**타켓값 분포도 확인**

In [14]:
df = pd.DataFrame(train.TARGET.value_counts())
df['Percentage'] = 100*df['TARGET']/train.shape[0]
df

   TARGET  Percentage
0   73012   96.043147
1    3008    3.956853

In [9]:
Data.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07,1.000000

## 3. 데이터 전처리

### 1) var3 : 국적(nationality of the customer)

In [15]:
train.var3.value_counts()[:10]

 2         74165
 8           138
-999999      116
 9           110
 3           108
 1           105
 13           98
 7            97
 4            86
 12           85
Name: var3, dtype: int64

In [17]:
train.loc[train.var3==-999999]

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
782,1567,-999999,33,0.0,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
3361,6738,-999999,36,0.0,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
4103,8225,-999999,27,0.0,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
4422,8879,-999999,45,0.0,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
7053,14142,-999999,44,0.0,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74796,149368,-999999,25,0.0,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
74846,149467,-999999,25,0.0,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
75012,149774,-999999,39,0.0,451.83,451.83,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
75783,151396,-999999,38,0.0,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
75968,151740,-999999,38,0.0,0.00,0.00,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93036.480000,0

**이상값 제거**

In [19]:
train_df = train.copy()
idx = train_df[train_df['var3']==-999999].index
train_df = train_df.drop(idx)
train_df

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76015,151829,2,48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60926.490000,0
76016,151830,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118634.520000,0
76017,151835,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74028.150000,0
76018,151836,2,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84278.160000,0
76019,151838,2,46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

### 2) 학습,  테스트 데이터 분리

In [20]:
X_features = train_df.iloc[:, :-1]
y_labels = train_df.iloc[:, -1]
print('피처 데이터 shape:{0}'.format(X_features.shape))

피처 데이터 shape:(75904, 370)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X_features, y_labels,
                                                    test_size=0.2, random_state=0, 
                                                    stratify = y_labels)
train_cnt = y_train.count()
test_cnt = y_test.count()
print('학습 세트 Shape:{0}, 테스트 세트 Shape:{1}'.format(X_train.shape , X_test.shape))

print(' 학습 세트 레이블 값 분포 비율')
print(y_train.value_counts()/train_cnt)
print('\n 테스트 세트 레이블 값 분포 비율')
print(y_test.value_counts()/test_cnt)

학습 세트 Shape:(60723, 370), 테스트 세트 Shape:(15181, 370)
 학습 세트 레이블 값 분포 비율
0    0.960394
1    0.039606
Name: TARGET, dtype: float64

 테스트 세트 레이블 값 분포 비율
0    0.960411
1    0.039589
Name: TARGET, dtype: float64

## 4. 모델 학습

In [27]:
model = XGBClassifier(missing=9999999999,
                max_depth = 5,
                n_estimators=1000,
                learning_rate=0.1, 
                nthread=4,
                subsample=1.0,
                colsample_bytree=0.5,
                min_child_weight = 3,
                reg_alpha=0.03,
                seed=1301)

model.fit(X_train, y_train, early_stopping_rounds=100,
         eval_metric="auc", eval_set =[(X_train, y_train),(X_test,y_test)])
xgb_roc_score = roc_auc_score(y_test, model.predict_proba(X_test)[:,1],average='macro')
print('ROC AUC: {0:.4f}'.format(xgb_roc_score))

[0]	validation_0-auc:0.818584	validation_1-auc:0.790776
Multiple eval metrics have been passed: 'validation_1-auc' will be used for early stopping.

Will train until validation_1-auc hasn't improved in 100 rounds.
[1]	validation_0-auc:0.828468	validation_1-auc:0.801507
[2]	validation_0-auc:0.826028	validation_1-auc:0.797602
[3]	validation_0-auc:0.827007	validation_1-auc:0.799738
[4]	validation_0-auc:0.825222	validation_1-auc:0.796658
[5]	validation_0-auc:0.822152	validation_1-auc:0.793894
[6]	validation_0-auc:0.829019	validation_1-auc:0.798783
[7]	validation_0-auc:0.835768	validation_1-auc:0.805692
[8]	validation_0-auc:0.833964	validation_1-auc:0.805078
[9]	validation_0-auc:0.832052	validation_1-auc:0.803081
[10]	validation_0-auc:0.830419	validation_1-auc:0.801882
[11]	validation_0-auc:0.829768	validation_1-auc:0.801093
[12]	validation_0-auc:0.828762	validation_1-auc:0.799607
[13]	validation_0-auc:0.833631	validation_1-auc:0.80417
[14]	validation_0-auc:0.832387	validation_1-auc:0.802995
[15]	validation_0-auc:0.830929	validation_1-auc:0.801227
[16]	validation_0-auc:0.836392	validation_1-auc:0.806513
[17]	validation_0-auc:0.84016	validation_1-auc:0.809824
[18]	validation_0-auc:0.842978	validation_1-auc:0.81191
[19]	validation_0-auc:0.842716	validation_1-auc:0.810958
[20]	validation_0-auc:0.845774	validation_1-auc:0.813933
[21]	validation_0-auc:0.845221	validation_1-auc:0.813111
[22]	validation_0-auc:0.845176	validation_1-auc:0.811511
[23]	validation_0-auc:0.848197	validation_1-auc:0.814685
[24]	validation_0-auc:0.847969	validation_1-auc:0.813451
[25]	validation_0-auc:0.847054	validation_1-auc:0.812135
[26]	validation_0-auc:0.850048	validation_1-auc:0.815432
[27]	validation_0-auc:0.850194	validation_1-auc:0.815767
[28]	validation_0-auc:0.852304	validation_1-auc:0.818069
[29]	validation_0-auc:0.851666	validation_1-auc:0.81703
[30]	validation_0-auc:0.851935	validation_1-auc:0.816443
[31]	validation_0-auc:0.851415	validation_1-auc:0.814916
[32]	validation_0-auc:0.854206	validation_1-auc:0.816679
[33]	validation_0-auc:0.856041	validation_1-auc:0.818792
[34]	validation_0-auc:0.857773	validation_1-auc:0.820724
[35]	validation_0-auc:0.857868	validation_1-auc:0.820544
[36]	validation_0-auc:0.859453	validation_1-auc:0.821875
[37]	validation_0-auc:0.859997	validation_1-auc:0.821761
[38]	validation_0-auc:0.861523	validation_1-auc:0.823265
[39]	validation_0-auc:0.862483	validation_1-auc:0.824293
[40]	validation_0-auc:0.86282	validation_1-auc:0.824169
[41]	validation_0-auc:0.863893	validation_1-auc:0.825087
[42]	validation_0-auc:0.865125	validation_1-auc:0.826144
[43]	validation_0-auc:0.865655	validation_1-auc:0.825953
[44]	validation_0-auc:0.866521	validation_1-auc:0.826941
[45]	validation_0-auc:0.867307	validation_1-auc:0.827831
[46]	validation_0-auc:0.868146	validation_1-auc:0.828539
[47]	validation_0-auc:0.868845	validation_1-auc:0.829064
[48]	validation_0-auc:0.869356	validation_1-auc:0.829458
[49]	validation_0-auc:0.869996	validation_1-auc:0.829505
[50]	validation_0-auc:0.870481	validation_1-auc:0.830176
[51]	validation_0-auc:0.871142	validation_1-auc:0.830076
[52]	validation_0-auc:0.871308	validation_1-auc:0.830494
[53]	validation_0-auc:0.871762	validation_1-auc:0.830809
[54]	validation_0-auc:0.872099	validation_1-auc:0.830654
[55]	validation_0-auc:0.872521	validation_1-auc:0.830713
[56]	validation_0-auc:0.872959	validation_1-auc:0.831173
[57]	validation_0-auc:0.873104	validation_1-auc:0.831128
[58]	validation_0-auc:0.87339	validation_1-auc:0.831067
[59]	validation_0-auc:0.873706	validation_1-auc:0.831518
[60]	validation_0-auc:0.874118	validation_1-auc:0.831923
[61]	validation_0-auc:0.874525	validation_1-auc:0.831997
[62]	validation_0-auc:0.87464	validation_1-auc:0.832002
[63]	validation_0-auc:0.874979	validation_1-auc:0.83185
[64]	validation_0-auc:0.875188	validation_1-auc:0.831794
[65]	validation_0-auc:0.875349	validation_1-auc:0.831691
[66]	validation_0-auc:0.875644	validation_1-auc:0.831591
[67]	validation_0-auc:0.876086	validation_1-auc:0.831341
[68]	validation_0-auc:0.876317	validation_1-auc:0.831241
[69]	validation_0-auc:0.876958	validation_1-auc:0.831349
[70]	validation_0-auc:0.877274	validation_1-auc:0.831543
[71]	validation_0-auc:0.877477	validation_1-auc:0.831632
[72]	validation_0-auc:0.877605	validation_1-auc:0.831519
[73]	validation_0-auc:0.877916	validation_1-auc:0.831623
[74]	validation_0-auc:0.878256	validation_1-auc:0.83163
[75]	validation_0-auc:0.87871	validation_1-auc:0.831787
[76]	validation_0-auc:0.878896	validation_1-auc:0.831805
[77]	validation_0-auc:0.87921	validation_1-auc:0.832018
[78]	validation_0-auc:0.879416	validation_1-auc:0.831942
[79]	validation_0-auc:0.879705	validation_1-auc:0.832201
[80]	validation_0-auc:0.879945	validation_1-auc:0.83243
[81]	validation_0-auc:0.8801	validation_1-auc:0.832265
[82]	validation_0-auc:0.88023	validation_1-auc:0.832408
[83]	validation_0-auc:0.8804	validation_1-auc:0.83223
[84]	validation_0-auc:0.880508	validation_1-auc:0.832147
[85]	validation_0-auc:0.880671	validation_1-auc:0.832047
[86]	validation_0-auc:0.880763	validation_1-auc:0.8321
[87]	validation_0-auc:0.881052	validation_1-auc:0.83208
[88]	validation_0-auc:0.881235	validation_1-auc:0.832007
[89]	validation_0-auc:0.881476	validation_1-auc:0.831929
[90]	validation_0-auc:0.88167	validation_1-auc:0.832
[91]	validation_0-auc:0.881848	validation_1-auc:0.831834
[92]	validation_0-auc:0.882053	validation_1-auc:0.831788
[93]	validation_0-auc:0.882257	validation_1-auc:0.831659
[94]	validation_0-auc:0.882337	validation_1-auc:0.831688
[95]	validation_0-auc:0.882877	validation_1-auc:0.831295
[96]	validation_0-auc:0.882942	validation_1-auc:0.831339
[97]	validation_0-auc:0.883185	validation_1-auc:0.831307
[98]	validation_0-auc:0.883271	validation_1-auc:0.831326
[99]	validation_0-auc:0.883303	validation_1-auc:0.831238
[100]	validation_0-auc:0.883424	validation_1-auc:0.831143
[101]	validation_0-auc:0.883539	validation_1-auc:0.831121
[102]	validation_0-auc:0.883631	validation_1-auc:0.831168
[103]	validation_0-auc:0.883964	validation_1-auc:0.830987
[104]	validation_0-auc:0.884216	validation_1-auc:0.830981
[105]	validation_0-auc:0.884241	validation_1-auc:0.83101
[106]	validation_0-auc:0.884292	validation_1-auc:0.831005
[107]	validation_0-auc:0.884849	validation_1-auc:0.830959
[108]	validation_0-auc:0.88495	validation_1-auc:0.83088
[109]	validation_0-auc:0.885112	validation_1-auc:0.830954
[110]	validation_0-auc:0.885244	validation_1-auc:0.830975
[111]	validation_0-auc:0.885427	validation_1-auc:0.831012
[112]	validation_0-auc:0.885828	validation_1-auc:0.831248
[113]	validation_0-auc:0.885922	validation_1-auc:0.831116
[114]	validation_0-auc:0.886009	validation_1-auc:0.831007
[115]	validation_0-auc:0.886241	validation_1-auc:0.830659
[116]	validation_0-auc:0.886317	validation_1-auc:0.830642
[117]	validation_0-auc:0.88655	validation_1-auc:0.83058
[118]	validation_0-auc:0.886702	validation_1-auc:0.830549
[119]	validation_0-auc:0.88695	validation_1-auc:0.830555
[120]	validation_0-auc:0.88712	validation_1-auc:0.830598
[121]	validation_0-auc:0.887311	validation_1-auc:0.830774
[122]	validation_0-auc:0.887625	validation_1-auc:0.830736
[123]	validation_0-auc:0.887903	validation_1-auc:0.830786
[124]	validation_0-auc:0.887996	validation_1-auc:0.830697
[125]	validation_0-auc:0.888069	validation_1-auc:0.830486
[126]	validation_0-auc:0.888377	validation_1-auc:0.830657
[127]	validation_0-auc:0.888597	validation_1-auc:0.830705
[128]	validation_0-auc:0.888713	validation_1-auc:0.830646
[129]	validation_0-auc:0.888757	validation_1-auc:0.83068
[130]	validation_0-auc:0.888868	validation_1-auc:0.830651
[131]	validation_0-auc:0.889163	validation_1-auc:0.830613
[132]	validation_0-auc:0.889284	validation_1-auc:0.830567
[133]	validation_0-auc:0.889423	validation_1-auc:0.830507
[134]	validation_0-auc:0.889458	validation_1-auc:0.830425
[135]	validation_0-auc:0.889805	validation_1-auc:0.830382
[136]	validation_0-auc:0.889881	validation_1-auc:0.830441
[137]	validation_0-auc:0.889943	validation_1-auc:0.830428
[138]	validation_0-auc:0.890285	validation_1-auc:0.830557
[139]	validation_0-auc:0.890449	validation_1-auc:0.830521
[140]	validation_0-auc:0.890512	validation_1-auc:0.83053
[141]	validation_0-auc:0.890546	validation_1-auc:0.830565

[142]	validation_0-auc:0.890803	validation_1-auc:0.830588
[143]	validation_0-auc:0.891264	validation_1-auc:0.830143
[144]	validation_0-auc:0.891359	validation_1-auc:0.830027
[145]	validation_0-auc:0.891771	validation_1-auc:0.830161
[146]	validation_0-auc:0.892034	validation_1-auc:0.8302
[147]	validation_0-auc:0.892303	validation_1-auc:0.829993
[148]	validation_0-auc:0.892424	validation_1-auc:0.829929
[149]	validation_0-auc:0.892588	validation_1-auc:0.829577
[150]	validation_0-auc:0.892739	validation_1-auc:0.829469
[151]	validation_0-auc:0.893011	validation_1-auc:0.829562
[152]	validation_0-auc:0.893267	validation_1-auc:0.829475
[153]	validation_0-auc:0.893367	validation_1-auc:0.829485
[154]	validation_0-auc:0.893742	validation_1-auc:0.829431
[155]	validation_0-auc:0.893849	validation_1-auc:0.829439
[156]	validation_0-auc:0.894039	validation_1-auc:0.829462
[157]	validation_0-auc:0.894198	validation_1-auc:0.829572
[158]	validation_0-auc:0.894423	validation_1-auc:0.82955
[159]	validation_0-auc:0.894465	validation_1-auc:0.829561
[160]	validation_0-auc:0.894675	validation_1-auc:0.829598
[161]	validation_0-auc:0.894973	validation_1-auc:0.829673
[162]	validation_0-auc:0.895343	validation_1-auc:0.829559
[163]	validation_0-auc:0.895616	validation_1-auc:0.829633
[164]	validation_0-auc:0.896076	validation_1-auc:0.829726
[165]	validation_0-auc:0.896171	validation_1-auc:0.82977
[166]	validation_0-auc:0.896567	validation_1-auc:0.829692
[167]	validation_0-auc:0.896612	validation_1-auc:0.829693
[168]	validation_0-auc:0.896961	validation_1-auc:0.829671
[169]	validation_0-auc:0.897263	validation_1-auc:0.829477
[170]	validation_0-auc:0.897527	validation_1-auc:0.82953
[171]	validation_0-auc:0.897583	validation_1-auc:0.829414
[172]	validation_0-auc:0.897645	validation_1-auc:0.829487
[173]	validation_0-auc:0.898066	validation_1-auc:0.829477
[174]	validation_0-auc:0.898203	validation_1-auc:0.829471
[175]	validation_0-auc:0.898263	validation_1-auc:0.829459
[176]	validation_0-auc:0.898568	validation_1-auc:0.829483
[177]	validation_0-auc:0.898918	validation_1-auc:0.829548
[178]	validation_0-auc:0.898994	validation_1-auc:0.829564
[179]	validation_0-auc:0.899152	validation_1-auc:0.829582
[180]	validation_0-auc:0.899187	validation_1-auc:0.829579
Stopping. Best iteration:
[80]	validation_0-auc:0.879945	validation_1-auc:0.83243

ROC AUC: 0.8324